apiVersion: v1
kind: Service
metadata:
  name: node-express-hello-world-service
spec:
  selector:
    app: node-express-hello-world
  ports:
    - protocol: TCP
      port: 3000       # ClusterIP port (internal)
      targetPort: 3000 # Port your app is running on inside the pod
  type: ClusterIP
